# Generated by Django 4.2.5 on 2023-09-30 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteRicetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(blank=True, max_length=100, null=True)),
                ('quantità', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredienti', models.ManyToManyField(to='main.ingredientericetta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spesa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ricettario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('immagine', models.ImageField(upload_to='img')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ricettario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ricetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ricetta_nome', models.CharField(max_length=100)),
                ('ricetta_descrizione', models.TextField()),
                ('ricetta_immagine', models.ImageField(upload_to='img')),
                ('ricetta_ingredienti', models.ManyToManyField(to='main.ingredientericetta')),
                ('ricettario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ricetta', to='main.ricettario')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('ricetta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ricetta', to='main.ricetta')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ricetta')),
            ],
        ),
    ]
